// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JZWLAc-My5QZx7VhSAH3aRkEEu-kLAk',
    appId: '1:327373595480:web:c21993e49652ff3df6fb2d',
    messagingSenderId: '327373595480',
    projectId: 'new-qi-apps-push-notif-5e963',
    authDomain: 'new-qi-apps-push-notif-5e963.firebaseapp.com',
    storageBucket: 'new-qi-apps-push-notif-5e963.appspot.com',
    measurementId: 'G-L5X1N0HW8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KEYJWbcRr-csvmTOy9Rkk4oBg6bJQLo',
    appId: '1:327373595480:android:6f41bb57110dfb8df6fb2d',
    messagingSenderId: '327373595480',
    projectId: 'new-qi-apps-push-notif-5e963',
    storageBucket: 'new-qi-apps-push-notif-5e963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjrMYZlep_YwmnABE9_CtMYd7SOIq0UE',
    appId: '1:327373595480:ios:a3bd72710f9d61b4f6fb2d',
    messagingSenderId: '327373595480',
    projectId: 'new-qi-apps-push-notif-5e963',
    storageBucket: 'new-qi-apps-push-notif-5e963.appspot.com',
    iosBundleId: 'com.example.newQiApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjrMYZlep_YwmnABE9_CtMYd7SOIq0UE',
    appId: '1:327373595480:ios:a3bd72710f9d61b4f6fb2d',
    messagingSenderId: '327373595480',
    projectId: 'new-qi-apps-push-notif-5e963',
    storageBucket: 'new-qi-apps-push-notif-5e963.appspot.com',
    iosBundleId: 'com.example.newQiApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JZWLAc-My5QZx7VhSAH3aRkEEu-kLAk',
    appId: '1:327373595480:web:b5191a0e37265cd8f6fb2d',
    messagingSenderId: '327373595480',
    projectId: 'new-qi-apps-push-notif-5e963',
    authDomain: 'new-qi-apps-push-notif-5e963.firebaseapp.com',
    storageBucket: 'new-qi-apps-push-notif-5e963.appspot.com',
    measurementId: 'G-7KFM86STQX',
  );
}
